Add missing include
On musl, this fails to build since basename(3) is undefined:

    /tmp/src/clr-rocm-6.4.3/rocclr/os/os_posix.cpp:736:27: error: 'basename' was not declared in this scope; did you mean 'rename'?
      736 |     appName = std::string(basename(buff.get()));
          |                           ^~~~~~~~
          |                           rename

Add the missing import.